### ISSUE TITLE
how do i start the app please ?

### ISSUE THREAD

**Issue by ihabdz55** [NormalPlayerJSH/lol-banpick-observer#2]
hello i have no idea  about the programming stuff i just want to open the app like shown in the exemple .
can you please guide me step by step how to  make it work ?
tnks

**Comment by ihabdz55** [comment]
@NormalPlayerJSH  help plz

**Comment by NormalPlayerJSH** [comment]
I have updated and released the excutable file.
Check [README.md](https://github.com/NormalPlayerJSH/lol-banpick-observer/blob/main/README.md).
