### ISSUE TITLE
how to change the korean text ?

### ISSUE THREAD

**Issue by ihabdz55** [NormalPlayerJSH/lol-banpick-observer#3]
hello thank you for your help earlier .
everything is working fine but i have a probleme i have no idea what the korean text says . how can i change it ?
i assume its the roles : like : top jungle mid adc supp ?? 
thank you for telling me how to fix this 
![dzdzdz](https://user-images.githubusercontent.com/88833836/173411001-887d41c9-4a05-4da0-90dc-3fe34bdf051c.png)

**Comment by NormalPlayerJSH** [comment]
That korean text is champion name.
Unfortunately, I don't have time to support English.
So it is recommended to turn off showing champ name.
Turn off 4th toggle button (챔피언 이름 표시 / Show Champion Name) on preference window.

**Comment by ihabdz55** [comment]
thank you so much for your help
